	# EMCS Labs.
	# This script is generated by ./local/make_path.sh. Therefore it might be different from other path.sh script.
	export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64
	export KALDI_ROOT=kaldiroot
	[ -f $KALDI_ROOT/tools/env.sh ] && . $KALDI_ROOT/tools/env.sh
	export PATH=./utils:./steps:$KALDI_ROOT/tools/openfst/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
	[ ! -f $KALDI_ROOT/tools/config/common_path.sh ] && echo >&2 "The standard file $KALDI_ROOT/tools/config/common_path.sh is not present -> Exit!" && exit 1
	. $KALDI_ROOT/tools/config/common_path.sh
	export LC_ALL=C
	ln -s $KALDI_ROOT/egs/wsj/s5/steps .
	ln -s $KALDI_ROOT/egs/wsj/s5/utils .
